from .Level import Level

one = Level("There's a directory called 'cdTest' within your current working path\nOpen this directory (Change your Directory to 'cdTest')\nThen please Print your current Working Directory to show that you have changed your directory\nNotice more text appears in your prompt, showing where you are in the filesystem\nYou may use the 'cd' command to open a directory\nType 'cd' followed by the name of the directory to open\nYou may type 'pwd' to PRINT your WORKING DIRECTORY\nNote: This is not the case with all terminals, it can be configured", "Type 'cd cdTest' and then 'pwd'", ("cd cdTest", "pwd"))
two = Level("So now you're in the 'cdTest' directory. Let's LiSt all of it's contents.\nYou can type 'ls' to list the contents in your current directory.\nIf you type 'ls' followed by the path to another directory, you can list the contents of that directory.", "Type 'ls'", ("ls",))
three = Level("Alright, let's get back to the home directory.\ncd with no other arguments will bring you to your home directory.", "Type 'cd' with no arguments", ("cd",))
four = Level("In each directory there are two 'links', one is a dir called '.' which points to the directory that contains it\nAnd a dir called '..' which points the directory that contains the current dir\nLet's put this into practice. Jump back into cdTest and get out using the '..' link.\nWatch the path displayed in your prompt to see the change, or type 'pwd'", "You can type 'cd cdTest' as before to get into the directory\nType 'cd ..' to use the link to get to the containing directory.", ("cd ..",))
five = Level("Now let's learn how to rename files. Jump into the directory called 'mvTest' and list it's contents, then rename the only file to 'newName'\nUse 'ls' to see the name change\nThe mv command is used to rename and move files, we'll move stuff in one second.", "Type 'mv from newName'", ("mv from newName",))
six = Level("Alright, let's move some files. MoVe the 'newName' file to the previous directory.\nWe use the 'mv' command for this as well. Instead of specifying a new name, you can give it a directory.\n Then list the contents of the directory and observe the change. Jump back to the previous directory and list the contents there, you'll see the moved file.", "You may type 'mv newName ..' to move it to the previous directory.", ("mv newName ..",))
seven = Level("Now let's CoPy a file. Copy the file called 'newName' and name the copy 'fileCopy'\nThen use 'ls' to see your changes", "Type 'cp newName fileCopy'", ("cp newName fileCopy",))
eight = Level("Okay. Now let's delete the original copy. The one called 'newName'.\n'rm' is the command for delete, comes from the word ReMove.", "Type 'rm newName'", ("rm newName",))
nine = Level("So we deleted a file, now let's delete a directory.\nThis can be accomplished using rm with the recursive (-r) flag, but we're gonna use the rmdir command, note this only works for empty directories.\nNow delete the mvTest directory", "Type 'rmdir mvTest'", ("rmdir mvTest",))
ten = Level("So how do we create directories? This is very easy, we use the 'mkdir' command which is derived from MaKe DiRectory.\nMake a directory called 'dirsAreEasy' and then cd into it", "Type 'mkdir dirsAreEasy' to make the directory", ("mkdir dirsAreEasy", "cd dirsAreEasy"))
eleven = Level("Now let's create a file. There's a few ways to do this, but let's use the touch command.\nMake a file called 'python'\nRemember to list the contents to see your changes.", "Type 'touch python'", ("touch python",))
twelve = Level("Okay. Let's add some text to this file.\nThere's a bunch of commands and programs to edit files.\nThis simulation has one called 'edit', follow it by a file name and you may edit the file.\nPress ctrl-d to exit and save.\nType anything you want in the file. Then exit and save.\nDO NOT PRESS CTRL-D ON THE SHELL OR IT WILL CRASH.", "Type 'edit python'", ("edit python",))
thirteen = Level("How do we check the contents of a file? There's a few methods.\nA common one is 'cat', which returns all the contents.\nLet's cat the file you just wrote to.\nNotice the contents.", "Type 'edit python'", ("edit python",))

levels = (one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen)